TRUNCATE TABLE ACCOUNT;
TRUNCATE TABLE PHONE;
TRUNCATE TABLE ADDRESS;
TRUNCATE TABLE MESSENGER;
TRUNCATE TABLE FRIEND;
TRUNCATE TABLE MESSAGE;
TRUNCATE TABLE INTERESTGROUP;
TRUNCATE TABLE GROUP_MEMBER;